let data = [
  {
    img: "dog-1.png",
    milesAway: "5",
    country: "USA",
    disability: "Parapalegic",
    cost: 136,
    id: 1,
    name: "Jane Doe",
  },
  {
    img: "dog-2.png",
    milesAway: "15",
    country: "USA",
    disability: "Partially Blind",
    cost: 47,
    id: 2,
    name: "Jane Doe",
  },
  {
    img: "dog-3.png",
    milesAway: "25",
    country: "USA",
    disability: "Urinary",
    cost: 98,
    id: 3,
    name: "Jane Doe",
  },
  {
    img: "dog-3.png",
    milesAway: "25",
    country: "USA",
    disability: "Urinary",
    cost: 98,
    id: 4,
    name: "Jane Doe",
  },
  {
    img: "dog-3.png",
    milesAway: "25",
    country: "USA",
    disability: "Urinary",
    cost: 98,
    id: 5,
    name: "Jane Doe",
  },
  {
    img: "dog-3.png",
    milesAway: "25",
    country: "USA",
    disability: "Urinary",
    cost: 98,
    id: 6,
    name: "Jane Doe",
  },
];

export default data;
